const quotes= [
    "No zobacz ile mam MS'u",
    "Kurwa, gość jest odpalony",
    "Dlatego proponuję grać faceity",
    "WH jak chuj",
    "Skąd on wiedział?",
    "Ta broń to gówno",
    "Zamknij pizdę",
    "Info z dupy",
    "Cyka Blyat",
    "Kurwa, w to się nie da grać",
    "kurwa, ruscy z aimbotem",
    "Znowu rusek w teamie",
    "English, motherfucker",
    "KURWA, ROTUJ!",
    "PLECY MACIE!",
    "Kurwa, mówiłem na A",
    "Kurwa, mówiłem na B",
    "CHUJOWY SMOKE CT",
    "KONEKTOR, KONEKTOR!!!",
    "Mówiłem, żebyś sprawdził",
    "Patrz tego mida!",
    "Sam byś tego nie ugrał",
    "Nice try",
    "Nie pushuj",
]
