const quotes = [
    "No zobacz ile mam MS'u",
    "Kurwa, gość jest odpalony",
    "Dlatego proponuję grać faceity",
    "WH jak chuj",
    "Skąd on wiedział?",
    "Ta broń to gówno",
    "Zamknij pizdę",
    "Info z dupy",
    "Cyka Blyat",
    "Kurwa, w to się nie da grać",
    "Kurwa, ruscy z aimbotem",
    "Znowu rusek w teamie",
    "English, motherfucker",
    "KURWA, ROTUJ!",
    "PLECY MACIE!",
    "Kurwa, mówiłem na A",
    "Kurwa, mówiłem na B",
    "CHUJOWY SMOKE CT",
    "KONEKTOR, KONEKTOR!!!",
    "Mówiłem Ci, żebyś sprawdził",
    "Patrz ktoś tego mida!",
    "Sam byś tego nie ugrał",
    "Nice try",
    "Nie pushuj",
    "Co robisz na tym A?",
    "Co robisz na tym B?",
    "Jak ty chujowo sprawdzasz miejscówki",
    "Dropnij awkę",
    "Dropnij kałacha",
    "Mam mleko",
    "Brawo Panowie",
    "Pamiętacie smoke'a?",
    "Tylko info",
    "Rucham ci matkę",
    "Pod drewnem!"
]
const AlreadyDrawn = []